import type { Product, VendorProfile } from "./types";

export const seedProducts: Product[] = [
  {
    id: 1,
    name: "Dell XPS 15",
    brand: "Dell",
    model: "XPS 15",
    price: 1899,
    cpu: "Intel Core i7",
    ram: "16GB",
    storage: "512GB SSD",
    gpu: "NVIDIA RTX 4050",
    screen: "15.6\"",
    condition: "new",
    warranty: "1 year",
    description: "Premium business laptop with high-resolution display.",
    category: "business",
    visible: true,
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=500",
  },
  {
    id: 2,
    name: "MacBook Pro 16\"",
    brand: "Apple",
    model: "MacBook Pro 16",
    price: 2499,
    cpu: "Apple M3 Pro",
    ram: "18GB",
    storage: "1TB SSD",
    gpu: "Integrated",
    screen: "16\"",
    condition: "new",
    warranty: "1 year",
    description: "Powerful laptop for creators and professionals.",
    category: "business",
    visible: true,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500",
  },
  {
    id: 3,
    name: "ASUS ROG Strix",
    brand: "ASUS",
    model: "ROG Strix",
    price: 1599,
    cpu: "Intel Core i7",
    ram: "16GB",
    storage: "1TB SSD",
    gpu: "NVIDIA RTX 4060",
    screen: "16\"",
    condition: "new",
    warranty: "1 year",
    description: "High-performance gaming laptop built for FPS.",
    category: "gaming",
    visible: false,
    image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500",
  },
];

export const seedProfile: VendorProfile = {
  shopName: "Tech Solutions Ltd",
  city: "New York",
  whatsapp: "+1 234 567 8900",
  description: "Premium laptop retailer specializing in business and gaming laptops.",
};
